version: "3.9"

services: 
    nginx:
        image: nginx
        build: requirements/nginx/
        container_name: nginx
        restart: always
        env_file: .env
        ports: 
            - "443:443"
        networks:
            - docker_network
        depends_on: 
            - wordpress
    mariadb:
        container_name: mariadb
        image: mariadb
        build: requirements/mariadb/
        restart: always
        env_file: .env
        volumes:
            - db
        networks: 
            - docker_network
    wordpress:
        container_name: wordpress
        image: wordpress
        build: requirements/wordpress/
        restart: always
        env_file: .env
        volumes:
            - wordpress
        networks: 
            - docker_network
        depends_on: 
            - mariadb
            

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/goinfre/awhana/virtual_machine/wordpress
    db:
        name: db
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/goinfre/awhana/virtual_machine/db

networks:
    docker_network:
        name: docker_network
        driver: bridge
