version: "3.8"

services: 
    nginx:
        container_name: nginx
        image: nginx
        build: requirements/nginx/
        restart: always
        env_file: .env
        ports: 
            - "443:443"
        volumes:
            - wordpress:/var/www/html/
        networks:
            - Inception
        depends_on: 
            - wordpress
    wordpress:
        container_name: wordpress
        image: wordpress
        build: requirements/wordpress/
        restart: always
        env_file: .env
        volumes:
            - wordpress:/var/www/html/
        networks: 
            - Inception
        depends_on: 
            - mariadb
    mariadb:
        container_name: mariadb
        image: mariadb
        build: requirements/mariadb/
        restart: always
        env_file: .env
        volumes:
            - db:/var/lib/mysql/
        networks: 
            - Inception

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/goinfre/virtual_machine/wordpress
    db:
        name: db
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/goinfre/virtual_machine/db

networks:
    docker_network:
        name: Inception
        driver: bridge
